### ISSUE TITLE
Methods used in other apex classes are also listed.

### ISSUE THREAD

**Issue by rajendrasnagar** [nawforce/apex-link#15]
I ran apex-assist 'find zombies' in my vs code. It listed 50k+ problems. I filtered by unused methods & cross checked. It lists methods which are used else where as well.

![image](https://user-images.githubusercontent.com/3901703/76955319-f4d5ee00-6937-11ea-8fae-51fbc6cb816e.png)

However, there are still methods which are not used elsewhere. So, this works but partly. 

Am i doing anything wrong here ?

**Comment by nawforce** [comment]
Hi Rajendra, sorry for taking some time to get to this. Can you test again and have a look in the VSCode 'Output' window (select apex-assist from the dropdown). You will see the log there. I am wondering if the files where the references are shown as processed or not.

**Comment by nawforce** [comment]
This has been dead for a while, closing.
