### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by codefriar** [nawforce/apex-link#30]
I've seen here in github that you've done more work here, but I'm not seeing a new version of apex-assist?

**Comment by nawforce** [comment]
I pushed out a 1.0.1 to fix a Windows issue and the Quiddty bug earlier in week. Your VSCode should have picked that up and updated itself.  If not you can show extensions needing updating with  command palette 'Show Outdated Extensions'. 

Just finished up on the SOSL bug, that will be in another update in next few days.

**Comment by nawforce** [comment]
Just pushed 1.1.0 out, your should get next time VSCode updates extensions.
