### ISSUE TITLE
False positives reported for missing properties on type declarations

### ISSUE THREAD

**Issue by jamessimone** [nawforce/apex-link#31]
Hi there - really loving the use of `apex-link` in conjunction with the VS Code plugin `Apex Assist`.

I've noticed there are a few missing properties on type declarations, leading to some false positives reported in the way of issues:

- `EventBus.ChangeEventHeader.changedFields` - https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_eventbus_ChangeEventHeader.htm
- `Formula` class within the `System` namespace - https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_class_System_Formula.htm#apex_class_System_Formula
- Missing type declaration for `ContactPointAddress` - https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contactpointaddress.htm (I'm also using `ContactPointEmail`, released at the same time; curiously, there are no issues with that object ...)

**Comment by nawforce** [comment]
Hi James, glad you are finding it useful and thanks for reporting these.  They all look like pretty straight forward omissions to correct so I will get them updated for the next release which will likely be towards the end of next week.

**Comment by jamessimone** [comment]
@nawforce thanks so much for the prompt response. Sounds great.
