### ISSUE TITLE
VSCode Plugin "Unknown field"

### ISSUE THREAD

**Issue by PawelWozniak** [nawforce/apex-link#34]
I am writing it here as link from VSCode plugin to repository point to this repo.
Found false error. As shown below, sobjects schema definition was build (even twice to be sure) but still it show an error that field do not exists. 
![image](https://user-images.githubusercontent.com/5740564/112341734-f44a0300-8cc1-11eb-92bf-70c1eda57e19.png)

I know that code is missing declaration for variable but it is not my code.

**Comment by nawforce** [comment]
I asume Parent_Quote__c here is a custom field that you have added. Generally you are going to see this error if the metadata for that custom field is not included in the workspace that you have opened in VSCode.  Unlike the Salesforce tools the analysis does not look at what is installed on your org but only at what metadata you have in your workspace.

If the metadata is in the workspace there could be a few reasons it is not being found. Probably the easy way to find out what is happening is to take a look at the output panel (View->Output & then select 'Apex Assist' from the dropdown. If you could post the output I can take a closer look.

**Comment by carlosabella** [comment]
Hi, I am facing the same problem but with Custom Objects. I followed your directions to see the output panel: 
{"$type":"com.nawforce.common.diagnostics.Issue","path":"/Users/cgarcia/SalesforceProjects/dev13_31032021/force-app/main/default/classes/TestClass.cls","diagnostic":{"category":{"$type":"DiagnosticCategory","value":"Missing"},"location":{"startLine":123,"startPosition":12,"endLine":123,"endPosition":33},"message":"No type declaration found for 'Schema.Git_Repository__c'"}}]}}

My sobject "Git_Repository__c" exists and it is inside ".sfdx/tools/sobjects/customObjects" folder. 

Thanks for your help. If you need more info, feel free to ask.

**Comment by nawforce** [comment]
The '.sfdx' folder is created by the Salesforce Apex extension from data it gathers from the org. Although I could read what is in there it is undocumented and there is some guidance from Salesforce not to rely on its contents. For my extension to work it will need to have the object metadata in your workspace, likely in somewhere like 'force-app/main/default/objects/Git_Repository__c'. If it was there then it will find it and know the object exists, if not then you will get an error.

Having said this I am considering if I should change the behaviour to go get metadata from the org if it's can't be found in the workspace. This would require a new feature so it's going to take a little while to change how the extension works.

**Comment by carlosabella** [comment]
Hi again, 

Now I get how your extension works. Thanks a lot for your explanation! very helpful :) 

I only have to add, VSCode extensions rely on .sfdx cache information, for instance, Intellisense is based on  the content cached here: ".sfdx/tools/sobjects/" folder. From my perspective using that folder could be safe. It sounds a bit weird Salesforce guidance not to rely on this folder content when they use it  for their own extensions. You can find more information here: https://www.lopau.com/how-to-enable-sobject-intellisense-in-vscode-for-salesforce-dx/

Regarding how to get metadata if it can't be found in the workspace ... nowadays the extension is forcing the developer to have the metadata information into the "objects" folder but when developing you don't need it the most of the situations (at least, from my experience) but, Sfdx is providing you tools like : Refresh Sobjects definition to cache that information in your local. 

I am just pretending to give ideas ... your extension is amazing :) Also I totally get this new feature will take time. 

Thanks a lot for your contribution to the Salesforce ecosystem!

**Comment by nawforce** [comment]
Yeah, it is a bit frustrating that they are advising against using this. I have created a new issues for looking at this (#40). I want to do some more work on false positives next but once that is over I should have time to take a look at implementing.
