### ISSUE TITLE
VSCode plugin. Installed package namespace is taken as not existing variable

### ISSUE THREAD

**Issue by PawelWozniak** [nawforce/apex-link#35]
We have installed overcast SAP integration plugin and it seems that namespace is taken as not existing variable.
![image](https://user-images.githubusercontent.com/5740564/112342510-90740a00-8cc2-11eb-842e-93534b0830c8.png)

Installed package component
![image](https://user-images.githubusercontent.com/5740564/112343607-974f4c80-8cc3-11eb-9791-128bfe556af6.png)

**Comment by nawforce** [comment]
Hi Paweł, 

You should be able to workaround this by declaring the namespace in your sfdx-project.json file. You need to add an entry that looks like this.

```
"plugins": {
    "dependencies": [
        {"namespace": "aa"}
    ]
}
```

This basically tells the analysis code that if it sees the namespace if should just assume all is well and not report an error.
