### ISSUE TITLE
A number of other false positives

### ISSUE THREAD

**Issue by jamessimone** [nawforce/apex-link#36]
Hi there, and thanks again for #32, that cleared out all of the false positives I had on [Rollup](https://github.com/jamessimone/apex-rollup), which in and of itself has been a significant quality of life improvement as far as my open source work goes.

At work, I'm still running into false positives grouped into a number of different areas:

- some, like #34, are due to the packages that I'm working on having _other_ 2gp package dependencies. Any chance of being able to walk the `**.d.ts` files in `.sfdx/typings/sobjects/` for this sort of thing?

Found due to the usage of [Nebula Logger](https://github.com/jongpie/NebulaLogger):

- one may be specific to platform events: `Unknown field or type 'CreatedById' on Schema.LogEntryEvent__c`
- missing method on enums:  `No matching method found for 'ordinal' on System.LoggingLevel taking no arguments` 
- missing static method on the `System.Limits` class: `No matching method found for 'getPublishImmediateDml' on System.Limits taking no arguments`

Found in general:

- Missing field on `Schema.BatchApexErrorEvent`:  `Unknown field or type 'Phase' on Schema.BatchApexErrorEvent` (Phase itself is a string ... even though it should definitely be an enum!)

In general, I'll close by saying that this plugin is really a game-changer for local Apex development, and I'm extremely appreciative you made it!

**Comment by nawforce** [comment]
Thanks for the issues and glad you are still enjoying it. I was just setting up a better test pipe so I will include these projects in it and resolve the issues. 

Looks like there is some [work](https://github.com/forcedotcom/salesforcedx-vscode/pull/3018) going on around the typing generation. I am a bit nervous of depending on that directly unless it's starts getting stable. I don't really do any work with 2GP but have been thinking about better support as its going to create a few challenges for some work tooling based off of this. Let me think it over and I will get back to you.

**Comment by nawforce** [comment]
Closed in error, doh.

**Comment by jamessimone** [comment]
NP - I completely get the 2GP stuff being much more complicated. The rest sounds good!

**Comment by nawforce** [comment]
I have fixed those issues, expecting I will release a patch in a few days so you should see them resolved then.

**Comment by jamessimone** [comment]
@nawforce awesome, looking forward to it - definitely evangelizing for this plugin, it’s a game-changer!

**Comment by nawforce** [comment]
Thanks, I certainly would not be without it these days. I turned off the SF Apex extension about 6 months back and have not returned to it ;-) I have released a patch version that should resolve the issues so I will close this now. There is a new issue (#40) for .sfdx/org retrieve handling. I am going to another round of false positive fixes next and then I should be free to start looking at it.

**Comment by jamessimone** [comment]
@nawforce now if this plugin had intellisense I _would_ disable the SF Apex extension, it's way too much of a memory hog at present. 😅

I can confirm that the patch fixed the rest of my false positives - thanks again!
