### ISSUE TITLE
Support importing metadata from .sfdx and/or org

### ISSUE THREAD

**Issue by nawforce** [nawforce/apex-link#40]
To handle this we need to introduce the idea of layers in the package structure. This is also needed for multi-package directory handling and 2GP dependencies. At the same time the restriction around SObject order resolving which impacts rollups needs to be fixed.

Just importing from .sfdx is likely not going to be sufficient for some (many?) projects as we need access to other metadata to complete the analysis. However if the data can be shown to be stable then it would be quicker than retrieving from an Org. This suggests a lazy evaluation might be the best option where local metadata take precedence over .sfdx and ultimately metadata needed from an org.

This is quite a bit of work so finding a way to stagger the features delivered might be useful.

See also #36 & #34.

**Comment by CarlParmenterCLDPartners** [comment]
Perhaps some way to "mute" certain categories of errors and warnings might help in the meantime?  Maybe something like an exclusion list setting?

It would also be nice to be able to use the dependency grapher only without having to use the code validation - turn off code validation altogether.

Thank you.

**Comment by nawforce** [comment]
Hi Carl, As it happens I am just doing final testing on a feature to download metadata. Should be released early next week I would hope.  Not sure quite how robust it will be in the first version, but working well for me on some large projects.

**Comment by CarlParmenterCLDPartners** [comment]
Very cool!  I'll try it out.

**Comment by nawforce** [comment]
This is released now, little demo vid at [youtu.be/B4lznOZ7Wts](https://t.co/PnI9NvkPcQ).

**Comment by nawforce** [comment]
Ah, thats a snag I should have fixed. The VSCode commands don't get registered until the extension has finished loading so if you are a bit quick you can can get this. If you look at the status bar after VSCode starts you should see 'Apex Assist' appear, when that goes away it is loaded and the command should run. 

I will add a bug for this to get a better message on it.

**Comment by CarlParmenterCLDPartners** [comment]
Thank you for following up!

**Comment by CarlParmenterCLDPartners** [comment]
Failed to download metadata - TypeError: Cannot read properties of null (reading 'localeCompare')

**Comment by nawforce** [comment]
Sorry, some teething troubles. I have just pushed out a 1.7.1 that should fix that for you.

**Comment by CarlParmenterCLDPartners** [comment]
Thank you.  I will try it out.

**Comment by CarlParmenterCLDPartners** [comment]
It looks like downloading metadata wipes out the whole gulp directory every time.  I tried to run it for "unmanaged", then a managed namespace, etc.  It was baffling at first, but I see that after downloading several namespaces, if I run it again on "unmanaged" it wipes everything out.  

Looks like one has to list all the namespaces at once (which doesn't scale well in a large, mature org with lots of packages.).

It also does not seem to run in parallel (which makes sense given the above).  If I launch a metadata download one a second namespace while a first one is downloading, it throws the previously mentioned error.

**Comment by CarlParmenterCLDPartners** [comment]
Looks like it's applying checks to the generated class signature stubs - and displaying thousands of errors on them.

Unexpected token '@'.

missing {'after', 'before', 'get', 'inherited', 'instanceof', 'set', 'sharing', 'switch', 'transient', 'trigger', 'when', 'with', 'without', 'select', 'count', 'from', 'as', 'using', 'scope', 'where', 'order', 'by', 'limit', 'and', 'or', 'not', 'avg', 'count_distinct', 'min', 'max', 'sum', 'typeof', 'end', 'then', 'like', 'in', 'includes', 'excludes', 'asc', 'desc', 'nulls', 'first', 'last', 'group', 'all', 'rows', 'view', 'having', 'rollup', 'tolabel', 'offset', 'data', 'category', 'at', 'above', 'below', 'above_or_below', 'security_enforced', 'reference', 'cube', 'format', 'tracking', 'viewstat', 'custom', 'standard', 'calendar_month', 'calendar_quarter', 'calendar_year', 'day_in_month', 'day_in_week', 'day_in_year', 'day_only', 'fiscal_month', 'fiscal_quarter', 'fiscal_year', 'hour_in_day', 'week_in_month', 'week_in_year', 'converttimezone', 'yesterday', 'today', 'tomorrow', 'last_week', 'this_week', 'next_week', 'last_month', 'this_month', 'next_month', 'last_90_days', 'next_90_days', 'last_n_days', 'next_n_days', 'next_n_weeks', 'last_n_weeks', 'next_n_months', 'last_n_months', 'this_quarter', 'last_quarted', 'next_quarter', 'next_n_quarters', 'last_n_quarters', 'this_year', 'last_year', 'next_year', 'next_n_years', 'last_n_years', 'this_fiscal_quarter', 'last_fiscal_quarter', 'next_fiscal_quarter', 'next_n_fiscal_quarters', 'last_n_fiscal_quarters', 'this_fiscal_year', 'last_fiscal_year', 'next_fiscal_year', 'next_n_fiscal_years', 'last_n_fiscal_years', IntegralCurrencyLiteral, 'find', 'email', 'name', 'phone', 'sidebar', 'fields', 'metadata', 'pricebookid', 'network', 'snippet', 'target_length', 'division', 'returning', 'listview', Identifier} at 'WebService'

**Comment by CarlParmenterCLDPartners** [comment]
I'd also note that it looks like the gulp folders look more or less like what gets downloaded into a DX formatted VS project project.  I already have a lot of the apparently missing metadata downloaded in my project.  Seems like it could use the already-downloaded metadata in the project first, then fall back to the gulp folder if not found.

Thanks very much.

**Comment by nawforce** [comment]
Hum, looks like things did not go so well. 

I did take the view that it was better to avoid incremental downloading as otherwise it just makes it very hard to understand if something is then stale, so yes its setup to download what you need in a single pass. I may be able to relax that a bit and just deal with each namespace as an independent thing. A bit of complication here is where you have dependencies between the namespaces, at the moment you have to order because that becomes important when loading metadata for analysis. Ideally I would like to find an automatic means of dealing with that problem.

In a similar vain I have been wondering about how to manage the overlap problem where some of the metadata may already be being held locally. That is probably solvable but would require a bit of work to add some additional smarts to the download mechanism so it could check what is already known about. That also overlaps a bit with better handling for packages without namespaces.

The web service should have been fine, the parser is well tested on a lot of Apex code, which is not a guarantee but its pretty rare to find any parsing issues. What I did worry about here though was how well formed what we are downloading is. I was thinking about disabling the validation on that and did make some changes due problems with the stubs, but its a bit chicken/egg, if we can't validate the stub OK then further analysis is at risk, so I think I probably just need to deal with stub issues as they arise to make this workable. 

Thanks for taking a look. If there is anything you can pass on about the stub issues I would be happy to take a look and see if I can resolve them.

**Comment by CarlParmenterCLDPartners** [comment]
Thanks for the response Kevin.

Imagine a VS Code project that is all classes and triggers in a large, complicated org - 30+ managed packages and hundreds of classes with references to each other and to managed artifacts...  Just entering all the namespaces at once is a challenge.  Perhaps the tool just isn't geared to this sort of scenario.

Perhaps one approach might be download all metadata for all namespaces at once - a "*" option or different command palette command that is not specific to namespaces...



I'll think about this and try it out some more as I can.

Thank you.
