### ISSUE TITLE
__r lookup object references not understood

### ISSUE THREAD

**Issue by JmeG** [nawforce/apex-link#6]
Error: line 320 at 34-67: Unknown field or type 'Sales_Specialist__r' on 'Schema.Lead'

```
List<Lead> convertedLeads = [
  SELECT Id, Sales_Specialist__r.Id, Sales_Specialist__r.Specialist_Type__c
  FROM Lead
  WHERE Id IN :leadIds AND Sales_Specialist__c != null
];

for (Lead convertedLead: convertedLeads) {
  User specialist = convertedLead.Sales_Specialist__r;
}
```

**Comment by nawforce** [comment]
Not been able to reproduce this one, could you share how Sales_Specialist__c is being defined thanks.

**Comment by JmeG** [comment]
Sales_Specialist__c is defined as a Lookup for the User object

**Comment by nawforce** [comment]
This has been dead for a while, closing.
