### ISSUE TITLE
KnowledgeArticleVersion isn't supported?

### ISSUE THREAD

**Issue by Confirm4Crit** [nawforce/apex-link#63]
Just leaving this as a note now, and will dig in later, but Apex Assist isn't supporting `KnowledgeArticleVersion`.
I'll do some more debugging between now and end of week to see if I can nail it down.

**Comment by nawforce** [comment]
Looks like I am missing a few of the SObjects in this area. Likely its because I have not enabled Knowledge in the org I use to pull the SObject describe information from. I will see if I can get that done and re-generate.

**Comment by nawforce** [comment]
Sorry for delay on this, I have merged the changes from turning on Knowledge. This will be in next version which should be available in about a week or so from now.

**Comment by Confirm4Crit** [comment]
you're a legend!
