### ISSUE TITLE
Server died! code: -1, signal: null

### ISSUE THREAD

**Issue by PawelWozniak** [nawforce/apex-link#90]
Hi I am having such issue when VSCode load. Any idea what could cause it?

Apex Assist activated
Spawning 'java -Xmx512m -Dfile.encoding=UTF-8 -cp jars/apexlink-2.3.3.jar com.nawforce.apexlink.cmds.Server'
Server ID: /C:/Users/pwozn/.vscode/extensions/kevinjones.apex-assist-1.7.1/jars/apexlink-2.3.3.jar
Server: [info] Org created in 11117ms with autoFlush = true, build = bd394a5579a53152d499ce835a9b6e2d4ae4e6f1
Server: java.lang.NullPointerException: Cannot invoke "org.antlr.v4.runtime.Token.getLine()" because "context.stop" is null
Server: 	at com.nawforce.runtime.parsers.Source.stampLocation(Source.scala:96)
Server: 	at com.nawforce.apexlink.cst.CST.withContext(CST.scala:39)
Server: 	at com.nawforce.apexlink.cst.Expression$.construct(Expressions.scala:903)
Server: 	at com.nawforce.apexlink.cst.ExpressionStatement$.construct(Statements.scala:592)
Server: 	at com.nawforce.apexlink.cst.Statement$.$anonfun$construct$60(Statements.scala:706)
Server: 	at scala.Option.map(Option.scala:242)
Server: 	at com.nawforce.apexlink.cst.Statement$.$anonfun$construct$59(Statements.scala:706)
Server: 	at scala.Option.orElse(Option.scala:477)
Server: 	at com.nawforce.apexlink.cst.Statement$.construct(Statements.scala:706)
Server: 	at com.nawforce.apexlink.cst.Statement$.$anonfun$construct$21(Statements.scala:602)
Server: 	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
Server: 	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
Server: 	at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
Server: 	at com.nawforce.apexlink.cst.Statement$.construct(Statements.scala:602)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.createStatements(Statements.scala:96)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.$anonfun$statements$3(Statements.scala:82)
Server: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Server: 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.statements(Statements.scala:80)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.verify(Statements.scala:58)
Server: 	at com.nawforce.apexlink.cst.ApexMethodDeclaration.$anonfun$verify$3(BodyDeclarations.scala:283)
Server: 	at com.nawforce.apexlink.cst.ApexMethodDeclaration.$anonfun$verify$3$adapted(BodyDeclarations.scala:282)
Server: 	at scala.Option.foreach(Option.scala:437)
Server: 	at com.nawforce.apexlink.cst.ApexMethodDeclaration.verify(BodyDeclarations.scala:282)
Server: 	at com.nawforce.apexlink.cst.ClassBodyDeclaration.validate(BodyDeclarations.scala:75)
Server: 	at com.nawforce.apexlink.types.apex.FullDeclaration.$anonfun$verify$5(FullDeclaration.scala:183)
Server: 	at com.nawforce.apexlink.types.apex.FullDeclaration.$anonfun$verify$5$adapted(FullDeclaration.scala:183)
Server: 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
Server: 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
Server: 	at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
Server: 	at com.nawforce.apexlink.types.apex.FullDeclaration.verify(FullDeclaration.scala:183)
Server: 	at com.nawforce.apexlink.cst.ClassDeclaration.verify(TypeDeclarations.scala:78)
Server: 	at com.nawforce.apexlink.types.apex.FullDeclaration.$anonfun$validate$2(FullDeclaration.scala:120)
Server: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Server: 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
Server: 	at com.nawforce.apexlink.types.apex.FullDeclaration.$anonfun$validate$1(FullDeclaration.scala:117)
Server: 	at com.nawforce.apexlink.types.apex.FullDeclaration.validate(FullDeclaration.scala:117)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$parseAndValidateClasses$5(StreamDeployer.scala:152)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$parseAndValidateClasses$5$adapted(StreamDeployer.scala:152)
Server: 	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
Server: 	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
Server: 	at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$parseAndValidateClasses$1(StreamDeployer.scala:152)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.parseAndValidateClasses(StreamDeployer.scala:133)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.consumeClasses(StreamDeployer.scala:128)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$load$1(StreamDeployer.scala:59)
Server: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Server: 	at com.nawforce.apexlink.types.platform.PlatformTypes$.withLoadingObserver(PlatformTypes.scala:69)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.load(StreamDeployer.scala:52)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.<init>(StreamDeployer.scala:45)
Server: 	at com.nawforce.apexlink.org.Module.freeze(Module.scala:62)
Server: 	at com.nawforce.apexlink.org.PackageImpl.$anonfun$freeze$1(PackageImpl.scala:61)
Server: 	at com.nawforce.apexlink.org.PackageImpl.$anonfun$freeze$1$adapted(PackageImpl.scala:61)
Server: 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
Server: 	at com.nawforce.apexlink.org.PackageImpl.freeze(PackageImpl.scala:61)
Server: 	at com.nawforce.apexlink.org.OrgImpl.$anonfun$packages$11(OrgImpl.scala:110)
Server: 	at com.nawforce.apexlink.org.OrgImpl.$anonfun$packages$11$adapted(OrgImpl.scala:110)
Server: 	at scala.collection.immutable.List.foreach(List.scala:333)
Server: 	at com.nawforce.apexlink.org.OrgImpl.$anonfun$packages$1(OrgImpl.scala:110)
Server: 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
Server: 	at com.nawforce.apexlink.org.OrgImpl.<init>(OrgImpl.scala:74)
Server: 	at com.nawforce.apexlink.api.Org$.$anonfun$newOrg$1(Org.scala:158)
Server: 	at com.nawforce.apexlink.api.Org$.newOrg(Org.scala:156)
Server: 	at com.nawforce.apexlink.api.Org$.newOrg(Org.scala:147)
Server: 	at com.nawforce.apexlink.rpc.OrgQueue.<init>(OrgAPIImpl.scala:32)
Server: 	at com.nawforce.apexlink.rpc.OrgQueue$.open(OrgAPIImpl.scala:419)
Server: 	at com.nawforce.apexlink.rpc.OrgAPIImpl.open(OrgAPIImpl.scala:448)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.$anonfun$new$42(RPCServer.scala:36)
Server: 	at scala.Option.map(Option.scala:242)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.$anonfun$new$40(RPCServer.scala:36)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.$anonfun$handleMessage$20(RPCServer.scala:64)
Server: 	at scala.util.Either.fold(Either.scala:189)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.handleMessage(RPCServer.scala:64)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.run(RPCServer.scala:54)
Server: 	at com.nawforce.apexlink.cmds.Server$.main(Server.scala:23)
Server: 	at com.nawforce.apexlink.cmds.Server.main(Server.scala)
Server died! code: -1, signal: null

**Comment by nawforce** [comment]
Sorry it's taken so long to respond on this, I ran into another problem that turned out to take quite a long time to resolve.

I have just pushed up a new version which has some extra debug in for this problem. If you could try that and let me know what you get in the exception we should be able to get this resolved.

**Comment by PawelWozniak** [comment]
I have sent you an email as the log is very big.
